PA-3512 | Testing gradle publish via pipeline
acquia/widen-jvm-threaddump pull request #5
Opened 2023-08-18 08:36 UTC by AbhishekRatnawat

**Motivation**

Fixes #NNN

**Proposed changes**

**Alternatives considered**

**Testing steps**

2023-12-11 08:20 UTC, AbhishekRatnawat commented on .acquia/Dockerfile.ci
> +FROM public.ecr.aws/amazoncorretto/amazoncorretto:11-al2022-jdk
```suggestion
FROM public.ecr.aws/amazoncorretto/amazoncorretto:11-al2023-jdk
```

2023-12-12 03:34 UTC, amanjoshicodes requested changes
Minor suggestions, Please add relevant screenshots and update PR description.

2023-12-12 03:34 UTC, amanjoshicodes commented on build.gradle
> +}
Please add new line at EOF.

2023-12-12 03:34 UTC, amanjoshicodes commented on build.gradle
> +    // version = 2.1.0-SNAPSHOT
Clean it up and Provide link to Java based repo onboarding doc that we have created as a comment here.

2023-12-12 03:34 UTC, amanjoshicodes commented on .acquia/pipeline.yaml
> +deploy:
Why are we encouraging `custom` deployment here?

2023-12-12 03:34 UTC, amanjoshicodes commented on .acquia/pipeline.yaml
> +  reason: "This is an internal/testing/no-production application. The vulnerabilities would be fixed by 2023/12/31 in ticketnumber PA-3838"
Please update the date, I'm skeptical that we would be able to address it by `2023/12/31`

2023-12-12 04:17 UTC, AbhishekRatnawat commented on .acquia/pipeline.yaml
> +deploy:
This application is not deploying anything. Included deploy section just to make package promotion work.

2023-12-12 04:22 UTC, AbhishekRatnawat commented on .acquia/pipeline.yaml
> +  reason: "This is an internal/testing/no-production application. The vulnerabilities would be fixed by 2023/12/31 in ticketnumber PA-3838"
```suggestion
  reason: "This is an internal/testing/no-production application. The vulnerabilities would be fixed by 2024/03/31 in ticketnumber PA-3838"
```

2023-12-12 04:22 UTC, AbhishekRatnawat commented on build.gradle
> +        // }
```suggestion
```

2023-12-12 04:22 UTC, AbhishekRatnawat commented on build.gradle
> +        //         }
```suggestion
```

2023-12-12 04:22 UTC, AbhishekRatnawat commented on build.gradle
> +    // version = 2.1.0-SNAPSHOT
```suggestion
```

2023-12-12 04:26 UTC, AbhishekRatnawat commented on build.gradle
> +}
```suggestion
}

```

2023-12-12 04:26 UTC, AbhishekRatnawat commented on build.gradle
>      group = 'widen'
```suggestion
// refer to: https://github.com/acquia/devops-pipeline/tree/master/consumer/java_projects_configurations.md to understand updated configurations in this file.
    group = 'widen'
```

2023-12-12 04:27 UTC, AbhishekRatnawat commented on build.gradle
> +// refer to: https://github.com/acquia/devops-pipeline/tree/master/consumer/java_projects_configurations.md to understand updated configurations in this file.
will update this link once the documentation is merged.

2023-12-12 04:27 UTC, AbhishekRatnawat commented on .acquia/pipeline.yaml
> +  reason: "This is an internal/testing/no-production application. The vulnerabilities would be fixed by 2023/12/31 in ticketnumber PA-3838"
done

2023-12-12 04:28 UTC, AbhishekRatnawat commented on build.gradle
> +    // version = 2.1.0-SNAPSHOT
done

2023-12-12 04:28 UTC, AbhishekRatnawat commented on build.gradle
> +}
done

2023-12-12 09:09 UTC, amanjoshicodes approved these changes
LGTM

2024-01-05 12:07 UTC, merged